#!/bin/bash
#Set up a directory structure for C++ projects using cmake

#Create directories
mkdir -p ./include
mkdir -p ./src
mkdir -p ./build

#Create CMakeLists.txt
cat > ./CMakeLists.txt <<EOL
cmake_minimum_required(VERSION 3.13.4)
set(CMAKE_CXX_STANDARD 17)
set(CMAKE_CXX_STANDARD_REQUIRED ON)
set(CMAKE_CXX_EXTENSIONS OFF)

project(INSERT_PROJECT_NAME)

#Bring headers into the project
include_directories(include)

#Create list of source files and add them to variable SOURCES
file(GLOB SOURCES "src/*.cpp")

add_executable(INSERT_EXECUTABLE_NAME \${SOURCES})
EOL

#Create main.cpp
cat > ./src/main.cpp <<EOL
#include <iostream>

int main(int argc, char *argv[]){
    std::cout << "Hello World!" << std::endl;
    return 0;
}
EOL
